// Comprehensive list of country codes
export const countryCodes = Object.freeze([
	{ id: 'us', code: '+1', country: 'United States' },
	{ id: 'ca', code: '+1', country: 'Canada' },
	{ id: 'ru', code: '+7', country: 'Russia' },
	{ id: 'kz', code: '+7', country: 'Kazakhstan' },
	{ id: 'eg', code: '+20', country: 'Egypt' },
	{ id: 'za', code: '+27', country: 'South Africa' },
	{ id: 'gr', code: '+30', country: 'Greece' },
	{ id: 'nl', code: '+31', country: 'Netherlands' },
	{ id: 'be', code: '+32', country: 'Belgium' },
	{ id: 'fr', code: '+33', country: 'France' },
	{ id: 'es', code: '+34', country: 'Spain' },
	{ id: 'hu', code: '+36', country: 'Hungary' },
	{ id: 'it', code: '+39', country: 'Italy' },
	{ id: 'ro', code: '+40', country: 'Romania' },
	{ id: 'ch', code: '+41', country: 'Switzerland' },
	{ id: 'at', code: '+43', country: 'Austria' },
	{ id: 'gb', code: '+44', country: 'United Kingdom' },
	{ id: 'dk', code: '+45', country: 'Denmark' },
	{ id: 'se', code: '+46', country: 'Sweden' },
	{ id: 'no', code: '+47', country: 'Norway' },
	{ id: 'pl', code: '+48', country: 'Poland' },
	{ id: 'de', code: '+49', country: 'Germany' },
	{ id: 'pe', code: '+51', country: 'Peru' },
	{ id: 'mx', code: '+52', country: 'Mexico' },
	{ id: 'cu', code: '+53', country: 'Cuba' },
	{ id: 'ar', code: '+54', country: 'Argentina' },
	{ id: 'br', code: '+55', country: 'Brazil' },
	{ id: 'cl', code: '+56', country: 'Chile' },
	{ id: 'co', code: '+57', country: 'Colombia' },
	{ id: 've', code: '+58', country: 'Venezuela' },
	{ id: 'my', code: '+60', country: 'Malaysia' },
	{ id: 'au', code: '+61', country: 'Australia' },
	{ id: 'id', code: '+62', country: 'Indonesia' },
	{ id: 'ph', code: '+63', country: 'Philippines' },
	{ id: 'nz', code: '+64', country: 'New Zealand' },
	{ id: 'sg', code: '+65', country: 'Singapore' },
	{ id: 'th', code: '+66', country: 'Thailand' },
	{ id: 'jp', code: '+81', country: 'Japan' },
	{ id: 'kr', code: '+82', country: 'South Korea' },
	{ id: 'vn', code: '+84', country: 'Vietnam' },
	{ id: 'cn', code: '+86', country: 'China' },
	{ id: 'tr', code: '+90', country: 'Turkey' },
	{ id: 'in', code: '+91', country: 'India' },
	{ id: 'pk', code: '+92', country: 'Pakistan' },
	{ id: 'af', code: '+93', country: 'Afghanistan' },
	{ id: 'lk', code: '+94', country: 'Sri Lanka' },
	{ id: 'mm', code: '+95', country: 'Myanmar' },
	{ id: 'ir', code: '+98', country: 'Iran' },
	{ id: 'ma', code: '+212', country: 'Morocco' },
	{ id: 'dz', code: '+213', country: 'Algeria' },
	{ id: 'tn', code: '+216', country: 'Tunisia' },
	{ id: 'ly', code: '+218', country: 'Libya' },
	{ id: 'gm', code: '+220', country: 'Gambia' },
	{ id: 'sn', code: '+221', country: 'Senegal' },
	{ id: 'mr', code: '+222', country: 'Mauritania' },
	{ id: 'ml', code: '+223', country: 'Mali' },
	{ id: 'ng', code: '+234', country: 'Nigeria' },
	{ id: 'ao', code: '+244', country: 'Angola' },
	{ id: 'et', code: '+251', country: 'Ethiopia' },
	{ id: 'ke', code: '+254', country: 'Kenya' },
	{ id: 'tz', code: '+255', country: 'Tanzania' },
	{ id: 'ug', code: '+256', country: 'Uganda' },
	{ id: 'zm', code: '+260', country: 'Zambia' },
	{ id: 'mg', code: '+261', country: 'Madagascar' },
	{ id: 'zw', code: '+263', country: 'Zimbabwe' },
	{ id: 'pt', code: '+351', country: 'Portugal' },
	{ id: 'lu', code: '+352', country: 'Luxembourg' },
	{ id: 'ie', code: '+353', country: 'Ireland' },
	{ id: 'is', code: '+354', country: 'Iceland' },
	{ id: 'al', code: '+355', country: 'Albania' },
	{ id: 'fi', code: '+358', country: 'Finland' },
	{ id: 'bg', code: '+359', country: 'Bulgaria' },
	{ id: 'lt', code: '+370', country: 'Lithuania' },
	{ id: 'lv', code: '+371', country: 'Latvia' },
	{ id: 'ee', code: '+372', country: 'Estonia' },
	{ id: 'ua', code: '+380', country: 'Ukraine' },
	{ id: 'rs', code: '+381', country: 'Serbia' },
	{ id: 'hr', code: '+385', country: 'Croatia' },
	{ id: 'si', code: '+386', country: 'Slovenia' },
	{ id: 'cz', code: '+420', country: 'Czech Republic' },
	{ id: 'sk', code: '+421', country: 'Slovakia' },
	{ id: 'sv', code: '+503', country: 'El Salvador' },
	{ id: 'hn', code: '+504', country: 'Honduras' },
	{ id: 'ni', code: '+505', country: 'Nicaragua' },
	{ id: 'cr', code: '+506', country: 'Costa Rica' },
	{ id: 'pa', code: '+507', country: 'Panama' },
	{ id: 'bo', code: '+591', country: 'Bolivia' },
	{ id: 'ec', code: '+593', country: 'Ecuador' },
	{ id: 'py', code: '+595', country: 'Paraguay' },
	{ id: 'uy', code: '+598', country: 'Uruguay' },
	{ id: 'bn', code: '+673', country: 'Brunei' },
	{ id: 'hk', code: '+852', country: 'Hong Kong' },
	{ id: 'mo', code: '+853', country: 'Macau' },
	{ id: 'kh', code: '+855', country: 'Cambodia' },
	{ id: 'la', code: '+856', country: 'Laos' },
	{ id: 'bd', code: '+880', country: 'Bangladesh' },
	{ id: 'tw', code: '+886', country: 'Taiwan' },
	{ id: 'mv', code: '+960', country: 'Maldives' },
	{ id: 'lb', code: '+961', country: 'Lebanon' },
	{ id: 'jo', code: '+962', country: 'Jordan' },
	{ id: 'sy', code: '+963', country: 'Syria' },
	{ id: 'iq', code: '+964', country: 'Iraq' },
	{ id: 'kw', code: '+965', country: 'Kuwait' },
	{ id: 'sa', code: '+966', country: 'Saudi Arabia' },
	{ id: 'ye', code: '+967', country: 'Yemen' },
	{ id: 'om', code: '+968', country: 'Oman' },
	{ id: 'ae', code: '+971', country: 'United Arab Emirates' },
	{ id: 'il', code: '+972', country: 'Israel' },
	{ id: 'bh', code: '+973', country: 'Bahrain' },
	{ id: 'qa', code: '+974', country: 'Qatar' },
	{ id: 'bt', code: '+975', country: 'Bhutan' },
	{ id: 'mn', code: '+976', country: 'Mongolia' },
	{ id: 'np', code: '+977', country: 'Nepal' },
	{ id: 'tj', code: '+992', country: 'Tajikistan' },
	{ id: 'tm', code: '+993', country: 'Turkmenistan' },
	{ id: 'az', code: '+994', country: 'Azerbaijan' },
	{ id: 'ge', code: '+995', country: 'Georgia' },
	{ id: 'kg', code: '+996', country: 'Kyrgyzstan' },
	{ id: 'uz', code: '+998', country: 'Uzbekistan' }
]);

export type CountryCode = (typeof countryCodes)[number];
